### ISSUE TITLE
unicode 13, 10 as last 2 characters check is not working in nmea.c

### ISSUE THREAD

**Issue by andrewhodel** [jacketizer/libnmea#12]
This works:

[nmea.c.txt](https://github.com/jacketizer/libnmea/files/674479/nmea.c.txt)

**Comment by andrewhodel** [comment]
With #define DEBUG

[nmea.c.txt](https://github.com/jacketizer/libnmea/files/674495/nmea.c.txt)

**Comment by jacketizer** [comment]
Thank you for finding the bug :-) I will look into it soon :-)

**Comment by jacketizer** [comment]
It is now fixed on master :-)
