### ISSUE TITLE
Issue with carriage return and linefeed

### ISSUE THREAD

**Issue by LaurinRossmeier** [jacketizer/libnmea#18]
Hello Jack,

First of all thank you very much for sharing this library which is pretty easy to understand even though I'm just a beginner. I'm using your library to parse nmea 0183 sentences coming from a gps and flarm module on the Raspberry PI and i have a issue which i need to fix. In the example program (minimum.c) you feed the parser with a gpggl sentence ending with "/n/n" but as you mention in the nmea.h (line 44) : 

```
/* NMEA sentence endings, should be \r\n according the NMEA 0183 standard */

#define NMEA_END_CHAR_1		'\n'
#define NMEA_END_CHAR_2		'\n'

```
As my Nmea sentences end with /r/n the nmea_validate  function rejects my sentence. 
I've also tried to change `NMEA_END_CHAR_1` to `'\r'` without sucess.

Please let me know how to handle this 

Thank you in advance , Laurin

**Comment by LaurinRossmeier** [comment]
I just fixed it!
So apparently when you just run `make`  it doesn't always update the header files.
if you use `make --always-make` it updates the header as well. 

Maybe you add this tip to the readme to help other people

Best Regards, Laurin

**Comment by jacketizer** [comment]
I think that my GPS module ends sentences with "\n\n" and that's probably why I used that in my example. However, it should be fixed to match the configuration in the header file.

I'm glad to hear that you think libnmea is easy to understand and hope that it will serve you well :-D If you have any problems or ideas for improvements, feel free to tell me. I will take a look at make issue :-)
