### ISSUE TITLE
Wrong NMEA SENTENCE LENGTH

### ISSUE THREAD

**Issue by muhammetasan** [jacketizer/libnmea#2]
It is stated that
```
 /* NMEA sentence max length (chars) */
#define NMEA_MAX_LENGTH		255 

```
 But the standard document IEC 61162 says that max length for NMEA 0183 is 82 chars including carriage return.

**Comment by jacketizer** [comment]
Good catch, thank you :-) I will fix it later today.

**Comment by jacketizer** [comment]
Fixed!
