### ISSUE TITLE
nmea sentence ending

### ISSUE THREAD

**Issue by andre-nguyen** [jacketizer/libnmea#29]
It is mentioned here https://github.com/jacketizer/libnmea/blob/master/src/nmea/nmea.h#L45
``` c++
/* NMEA sentence endings, should be \r\n according the NMEA 0183 standard */
#define NMEA_END_CHAR_1		'\n'
#define NMEA_END_CHAR_2		'\n'
```

That the sentence ending should be `\r\n`, however the code and examples define it as `\n\n`. I'm getting nmea GPRMC sentences from my equipment as `\r\n` I was wondering if this changes from vendor to vendor? Maybe we can change the code to accept both `\r\n` and `\n\n`.

**Comment by jacketizer** [comment]
Yes, I agree, so I changed it to `\r\n` in commit 5636040d15c094eedc83205e582c8f7d0d8bdebd.

Maybe a good solution would be to allow the sentence ending parsing to be configurable run-time, maybe by providing it as an argument etc?
