### ISSUE TITLE
Missing from readme

### ISSUE THREAD

**Issue by aramf** [jacketizer/libnmea#42]
The file parser.c has this towards the top of it:

```
/**
 * Where to find the parser modules.
 * Can be overridden by env variable NMEA_PARSER_PATH
 */
#define PARSER_PATH "/usr/lib/nmea/"
```

So if you are not putting your parser .so files in /usr/lib/nmea, you will need to define the variable NMEA_PARSER_PATH.

The readme should mention this.

**Comment by jacketizer** [comment]
Agree, I will fix it when I get some time.
