### ISSUE TITLE
Compiling with Cmake

### ISSUE THREAD

**Issue by JuhToiva** [jacketizer/libnmea#43]
Hi

We have been using the libnmea library on with esp32 and compiling using gcc make.
That has been working fine.

Now I am trying to get compiling working with Cmake.
All other components are now working, except the libnmea.
From it comes lot of problems starting from the thing that it is make for really old Cmake version 2.8 and now I have 3.19 in use.

Do you happen to have newer Cmake file for libnmea ?

BR Juha T.

**Comment by yhsb2k** [comment]
Hi @JuhToiva, maybe I can help you. Find updated CMake file here:
https://github.com/yhsb2k/omef/commit/f3c57972d9422bb57dc6cb9838cab899e66215c0

**Comment by igrr** [comment]
I think the issue about building for ESP32 was resolved in https://github.com/igrr/libnmea-esp32/issues/2, and this one can be closed.

**Comment by JuhToiva** [comment]
Hi

Yes from my side this is OK.

BR Juha T.
________________________________
Lähettäjä: Ivan Grokhotkov <notifications@github.com>
Lähetetty: tiistai 2. maaliskuuta 2021 19.39
Vastaanottaja: jacketizer/libnmea <libnmea@noreply.github.com>
Kopio: Juha Toivanen <juha.toivanen@sadeinnovations.com>; Mention <mention@noreply.github.com>
Aihe: Re: [jacketizer/libnmea] Compiling with Cmake (#43)


I think the issue about building for ESP32 was resolved in igrr/libnmea-esp32#2<https://github.com/igrr/libnmea-esp32/issues/2>, and this one can be closed.
