### ISSUE TITLE
time and date not being parsed correctly on ESP-IDF

### ISSUE THREAD

**Issue by stephenaa** [jacketizer/libnmea#48]
The newlib strptime() implementation on that platform is a bit too crude, and thus will parse all content into the first argument. 
I have a simple fix that copies the date or time string into a token separated string that the newlib strptime() can parse correctly. However, that seems a bit messy and considering that a similar problem can occur on other platforms I was wondering if another solution would be preferable? Such as a simpler implementation not using strptime() but instead parsing the time and date fields itself?

**Comment by igrr** [comment]
Yes, this is a [known issue](https://github.com/igrr/libnmea-esp32#known-issues). Please have a look at https://github.com/jacketizer/libnmea/pull/35 which may fix this. If you can test it or propose changes based on the fix you did, that would be appreciated!

**Comment by jacketizer** [comment]
I merged #34, but if writing a custom parsing implementation is better then I'm up for that :-)

**Comment by igrr** [comment]
Thanks, I'll update https://github.com/igrr/libnmea-esp32 to include the latest version of libnmea. Probably this issue can be closed.
