### ISSUE TITLE
Add "C" linkage

### ISSUE THREAD

**Issue by ndrego** [jacketizer/libnmea#5]
As it stands, the only way this library can be linked from C++ is to do the following:

```
extern "C" {
#include <nmea.h>
#include <nmea/gpgll.h>
#include <nmea/gpgga.h>
}
```
which is fine, except that it shouldn't be incumbent on the user to do so. Instead, the C linkage is usually taken care of *within* the header. Will you consider adding this to the headers so that the users do not have to spend hours figuring out why they keep getting errors like this:

```
...: undefined reference to `nmea_parse(char*, unsigned long, int)'
...: undefined reference to `nmea_free(nmea_s*)'
```

**Comment by jacketizer** [comment]
Sound good :-). Maybe a good solution is to add them to the header files at build-time using defines/preprocessor. I will try it when I have some time left.

**Comment by jacketizer** [comment]
There's a pull request out for review. You are more than welcome to take a look :-)
https://github.com/jacketizer/libnmea/pull/6

**Comment by jacketizer** [comment]
Merged to master.
